[package]
name = "bytepeep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.10", features = ["macros"] }
strum = "0.24"
strum_macros = "0.24"
colored = "2.0.0"